src/accounts/urls.py
from django.urls import path

from .views import RegisterView, changeUsername

app_name = 'accounts'

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("changedmymind/", changeUsername, name="changedmymind")
]

src/history/urls.py
from django.urls import path

from .views import history, showPassword

app_name = "history"

urlpatterns = [
    path("", history, name="history"),
    path("show_password/<int:item_id>", showPassword, name="show_password")
]

src/items/urls.py
from django.urls import path

from .views import createItem, listItems, updateItem, deleteItem, showPassword, shareItem, sharedItems, delete_item_shared

app_name = "items"

urlpatterns = [
    path("create_item/", createItem, name="create_item"),
    path("items_list/", listItems, name="items_list"),
    path("share_item/<int:item_id>", shareItem, name="share_item"),
    path("update_item/<int:item_id>", updateItem, name="update_item"),
    path("delete_item/<int:item_id>", deleteItem, name="delete_item"),
    path("show_password/<int:item_id>", showPassword, name="show_password"),
    path("shared_items", sharedItems, name="shared_items"),
    path("shared_item/<int:shared_item_id>", delete_item_shared, name='delete_item_shared'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('history/', include("history.urls")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('items/', include("items.urls"))
]

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <script src="https://kit.fontawesome.com/c757229a79.js" crossorigin="anonymous"></script>
</head>
<body>
  {% load static %}
  <main class="container">
    <nav>
      <ul>
        <li><a href="{% url 'home' %}"><img style="max-width: 100px; margin-right: 50px;" src="{% static 'img/dj_logo.png' %}" alt="Logo de djangword"></a></li>
        <li><a href="{% url 'items:create_item' %}">Créer un item</a></li>
        <li><a href="{% url 'items:items_list' %}">Voir ses items</a></li>
        <li><a href="{% url 'items:shared_items' %}">Items partagés</a></li>
        <li><a href="{% url 'history:history' %}">Voir l'hitorique de ses items</a></li>
      </ul>
      <ul>
        <li><a href="{% url 'accounts:changedmymind' %}" >Changer son mot de passe</a></li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
  </main>
  {% block script %}
  {% endblock %}
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
    <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}